# Generated by Django 6.0 on 2026-01-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=100)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('education', models.TextField()),
                ('course', models.TextField()),
                ('projects', models.TextField()),
                ('certifications', models.TextField(blank=True)),
                ('training', models.TextField(blank=True)),
                ('uploaded_resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('ats_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
